sudo: required
services:
  - docker

script:
  - docker build -t ahmeddesigns/node .
  - docker images ahmeddesigns/node

before_deploy: 
  - docker login -u ahomar -p A12345678

deploy: 
  provider: script
  script: docker push ahmeddesigns/node
  on:
    branch: master