sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before_deploy: 
  - docker login -U ahomar -P A12345678

deploy: 
  provider: script
  script: docker push mannydesigns/node
  on:
    branch: master